### ISSUE TITLE
Architecture en Micro Service 

### ISSUE THREAD

**Issue by peebee** [bflorat/modele-da#2]
Comment tu décriras une architecture en Micro service dans ce modèle

**Comment by bflorat** [comment]
Je ne vois rien de spécifique à une architecture µS concernant ce modèle qui peut aussi bien décrire un monolithe que tout type d'architecture d'informatique de gestion. Le gros du dossier, c'est recueillir les ENF (sécurité, performance, disponibilité, ...) et comment on les adresse. Ca ne changera pas avec des microservices. D'ailleurs, j'ai réalisé ce modèle avec des quasi-architectures micro-services en tête (DGFiP, SRE...)

La seule chose à voir, c'est le grain du dossier : module par module ou groupe de modules cohérents (par domaine ?). En µS, il n'y a plus vraiment d'application mais un découpage en nombreux modules de services, d'IHM et de batch faiblement couplés et petits. Faire tout un DA par module est peut être overkill mais reste conseillé.

Sinon, si tu comptes utiliser ce modèle, sache qu'une V3 va être disponible dans quelques jours ( voir https://gitlab.com/bflorat/modele-da/tree/develop en version dev). Je l'ai un peu augmenté mais surtout rendu un peu plus 'documentation vivante' : réécriture en asciidoc pour favoriser les merge requests et la genération auto du rendu. Diagrammes UML2 en cours de réécriture en C4 (toujours en plantuml). Tout retour apprécié.
