### ISSUE TITLE
Utilisation de offset dans les bonnes pratiques de performance

### ISSUE THREAD

**Issue by dossantospat** [bflorat/modele-da#24]
Bonjour,

Dans le volet développement, au paragraphe `5.2. Performances`, le premier exemple peut amener à des contre-performances.

L'utilisation du combo `OFFSET - LIMIT` n'empêche pas le SGDB de faire une requête avec tous éléments avant de n'en renvoyer qu'une partie.

C'est expliqué en détail dans cet article : https://use-the-index-luke.com/no-offset

Merci beaucoup pour votre travail ;)

**Comment by bflorat** [comment]
Merci pour ce retour. Corrigé sur version fr et en.
