### ISSUE TITLE
Ajouter outil d'export html

### ISSUE THREAD

**Issue by bflorat** [bflorat/modele-da#26]

**Comment by siwon** [comment]
Bonjour @bflorat,

Je ne sais pas si ça peut correspondre à votre besoin mais j'utilise un makefile pour réaliser l'export :

```
MAKEFLAGS += -j2

all: readme

copy_img:
	@echo "Sync images"
	@rsync -av --delete images exports_html/ > /dev/null 2>&1

readme: readme-pdf readme-html

readme-pdf:
	@echo "readme-pdf: running"
	@docker run --rm -v $(shell pwd):/documents -e TZ=Europe/Paris asciidoctor/docker-asciidoctor asciidoctor-pdf \
			-a pdf-output=true \
			-a pdf-themesdir=resources/themes \
			-a pdf-theme=default \
			-a relfilesuffix=.pdf@ \
			-o exports_pdf/documentation_nifi.pdf \
			README.adoc
	@echo "readme-pdf: done"

readme-html: copy_img
	@echo "readme-html: running"
	@docker run --rm -v $(shell pwd):/documents -e TZ=Europe/Paris asciidoctor/docker-asciidoctor asciidoctor \
			-a html-output=true \
			-a pdf-themesdir=resources/themes \
			-a pdf-theme=default \
			-a relfilesuffix=.html@ \
			-o exports_html/index.html \
			README.adoc
	@echo "readme-html: done"

clean:
	rm -rf exports_html/*
	rm -rf exports_pdf/*
```

Quelques informations concernant ce makefile :
* Les images sont toutes placées dans un dossier `images` à la racine du projet
* Les fichiers de templating sont placés dans le répertoire `resources/themes`
* Les fichiers sont générés dans des sous-dossiers de l'arborescence `exports_pdf` et `exports_html` (qu'il faudra ajouter au `.gitignore`)
* Il utilise docker et la commande `rsync` qu'il faudra installer au préalable.

Je ne sais pas si cela répond au besoin initial mais si ça peut aider :)

**Comment by bflorat** [comment]
Bonjour @siwon,

Ah, désolé, en fait ca existe déjà, j'avais oublié de fermer ce ticket , voir https://github.com/bflorat/modele-da/blob/master/modeles-vierges/export

qui exporte en PDF, html (images embedded) et odt..
