### ISSUE TITLE
Dimensionnement du stockage partagé

### ISSUE THREAD

**Issue by bflorat** [bflorat/modele-da#27]
Proposition de Paul Fievet : 

"Dans le document volet-architecture-dimensionnement.adoc, j’ai ajouté le paragraphe suivant, à la fin du document :

```
=== Dimensionnement du stockage partagé

[cols='1,3,3']

|====

|Profil (NAS/S3/Swift,...)|Taille (Gio)| Type de machine utilisant ce partage

 
|N/A|||

 |====
```
 

Je n’ai pas trouvé d’endroit pour mettre les tailles (initiales et prévisionnelles) des répertoires partagés."

**Comment by bflorat** [comment]
Merci Paul,

1) Qu'entend-tu exactement par stockage partagé ? entre quoi ? processus ? serveurs ? projets ? environnements ? zones réseau ? cloud ? datacenter ?
2) As-tu des explications et examples plus développés ?

**Comment by pfi93000** [comment]
J'ai 2 serveurs web et un espace de stockage objet (de type openstack swift dans mon cas) avec les pages statiques, je vois où mettre mes 2 serveurs et les disques pour le produit et les logs dans le document volet-architecture-dimensionnement.adoc, mais je ne vois pas où décrire la taille de mon espace disque partagé distant avec le contenu du site.

Ce pourrait être la même chose avec un NAS partagé entre plusieurs serveurs. Je ne vois pas où décrire la taille de ce NAS et ses besoins en évolution.

**Comment by bflorat** [comment]
Bonjour. 

J'utilise justement aussi du Swift sur mon projet actuel. J'intégre ces calculs dans une feuille LibreOffice séparée (avec un onglet par composant technique ou module), j'ai donc un onglet pour le swift, un autre pour le NAS, un autre pour chaque base,etc..). Dans le chapitre 4.1 du volet dimensionnement, je reprends simplement le volume global (voire je fais une simple reference vers la feuille LibreOffice). Comme décrit dans les tips, un tableur est beaucoup plus indiqué pour ce besoin.

Sur le fond, l'idée du volet dimensionnement est de référencer les besoins en volumétrie de tous les composants techniques (bases de données, NAS, logs, stockage objet...). 

Ce qui importe de mon point de vue concernant  le stockage  est d'être en mesure de donner aux ops : 
1) une enveloppe globale  pour tout le projet.
2) si besoin, de donner les besoins disque de chaque serveur ou composant mutualisé en vue de provisionner du disque et de ne pas tomber en 'No space left' au bout de 2 jours.
3) donner le volume initial et à 5 ans (pour prendre en compte l'augmentation de la volumétrie).

Dis-moi si tu veux un exemple de feuille LibreOffice...  (d'ailleurs je me demande si ce serait utile pour ce modèle...)

**Comment by pfi93000** [comment]
Le chapitre 3 et 4 décrivent les contraintes et les exigences et décrire les besoins.
Le chapitre 5, si j'ai bien compris, permet de conclure avec un dimensionnement et donc commander la première instance (ou son réachat en cas de perte du data-center de PROD).
Je ne vois pas où noter le stockage partagé dans le chapitre 5.

**Comment by bflorat** [comment]
OK, je comprends le besoin. Ta proposition me semble bien mais il faudrait la developper avec plus de conseils / exemples sur comme les autres paragraphes.

Plutot que 'Profil', je dirait 'nature' et plutot que de donner des exemples entre parenthese, je donnerais des exemples complets dans le tableau. Il faudrait aussi des explications 'Tips'.

Tu proposes une pull request ? Sinon, je fais une proposition.

**Comment by bflorat** [comment]
Voir PR#28, @bflorat : à reporter sur version EN
