### ISSUE TITLE
Syntaxe pour les titres : remplacer les `=` par des `#`

### ISSUE THREAD

**Issue by mgrzybek** [bflorat/modele-da#30]
Bonjour,

Le document utilise des `=` afin de créer les titres / sections de chaque volet.

Je suis en train de créer un export PDF qui concatène tous les volets en un seul document (avec `asciidoctor` et `pandoc` afin d’y appliquer un modèle *LaTeX*). Or, avec le modèle *book*, je dois descendre d’un cran toute la hiérarchie avec une expression rationnelle avant l’export. Il est plus facile de traiter des ajouts de dièses, caractère différent que ceux utilisés pour baliser les autres blocs du document.

Il faudrait donc utiliser des dièses pour baliser la hiérarchie des documents.

MG

**Comment by bflorat** [comment]
Pas de problème, c'est d'ailleurs ce que je fais sur mon projet actuel. Seul bemol : c'est du spécifique asciidoctor, pas du standard asciidoc mais tout le monde (y compris gitlab) utilise asciidoctor ou une version adaptée donc OK.

Pouvez-vous proposer une PR ?
