### ISSUE TITLE
Proposition d'intégration du RACI au volet sécurité

### ISSUE THREAD

**Issue by siwon** [bflorat/modele-da#36]
Bonjour,

Merci pour ce modèle qui m'est très utile.
Me concernant, j'ajoute souvent à votre modèle un dernier paragraphe au chapitre "sécurité" : un RACI.

Voici un exemple avec une catégorie :

```
== RACI

:r: pass:quotes[[.green]#R#]
:a: pass:quotes[[.red]#A#]
:c: pass:quotes[[.blue]#C#]
:i: pass:quotes[[.orange]#I#]
:na: pass:quotes[[.grey]#N/A#]
:et: pass:quotes[[.grey]#&amp;#]

* {r} : *Responsive* (personne qui va exécuter : elle en est responsable)
* {a} : *Accountable* (personne qui va approuver la tâche : elle en est l'autorité)
* {c} : *Consulted* (personne qui va être consultée dans l'exécution de la tâche)
* {i} : *Informed* (personne qui sera informée lorsque la tâche est terminée)

=== Gestion de la plateforme AWS

.Gestion de la plateforme AWS
[cols="6,^1,^1,^1,^1"]
|===
||Systemes & Cloud|Sécurité SI|Réseau|AWS

.^|Création des accounts AWS
.^|{r} {et} {a}
.^|{c} {et} {i}
.^|{a}
.^|

.^|Création des SCP AWS
.^|{r} {et} {a}
.^|{c} {et} {i}
.^|{a}
.^|
|===
```

Dans un PDF, ça donne ce rendu :
![image](https://user-images.githubusercontent.com/1249874/189838289-6b4419a1-cae3-47dd-85a5-b49802e5d7c7.png)

Si cela vous parait pertinent, je peux vous proposer une pull request.

Merci encore pour votre modèle et bonne journée.

**Comment by bflorat** [comment]
Merci @siwon,

Oui, ca m'a l'air utile à condition:
1) Que ca ne remplace pas un kanban ou un suivi d'avancement des taches (le DA ne doit pas couvrir la gestion de projet ) mais uniquement une présentation 'statique' des services en charge de chaque aspect. Effectivement, c'est un point important en sécurité de savoir qui fait quoi. 
2) que cela reste très générique

Dans le même esprit, il pourrait être bien d'avoir une section sur les études de risque et les pentests (qui / quand / critère de succès...).

Je veux bien une PR...

Sinon, j'aimerais amorcer une liste de references. Si c'est ok pour vous, pouvez vous donner le nom de votre organisation et le nb de projets qui utilisent ce modèle pour être listé (en privé, mon contact : https://florat.net/contact/index.html ) ?

**Comment by bflorat** [comment]
Chapitre ajouté
